version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sa1234
      - POSTGRES_DB=CatalogDb
    restart: always
    ports:
        - "5434:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/ 

  basketdb:
    container_name: basketdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sa1234
      - POSTGRES_DB=BasketDb
    restart: always
    ports:
        - "5435:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/
  
  distributedCache:
    container_name: distributedCache
    restart: always
    ports:
        - "6378:6379" 


  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=sa1234;Include Error Detail=true
    depends_on:
      - catalogdb
    ports:
      - "5400:8080"
      - "5460:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=sa1234;Include Error Detail=true
      - ConnectionStrings__Redis=distributedCache:6379
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081
    depends_on:
      - catalogdb
      - distributedCache
      - discount.grpc
    ports:
      - "5401:8080"
      - "5461:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=DiscountDb
    ports:
      - "5402:8080"
      - "5462:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
